---
sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo add-apt-repository ppa:jgross-h/graphviz -y
  - sudo apt-get update
  # - sudo apt-get remove libcdt4
  - sudo apt-get remove libpathplan4
  - sudo apt-get install -y graphviz

after_success:
  - cd slides/target/generated-slides
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
