---
services:
  - docker

cache:
  directories:
  - /tmp/m2

before_install:
  - mkdir -p /tmp/m2
  - docker build -t kstreams .

script:
  - docker run -v /tmp/m2:/root/.m2 -v $TRAVIS_BUILD_DIR:/data --rm kstreams /bin/bash -c "mvn verify"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: slides/target/generated-slides
  on:
    branch: master
